function(android_abi_to_compiler_prefix abi ret)
    if(abi STREQUAL "arm64-v8a")
        set(${ret} "aarch64-linux-android" PARENT_SCOPE)
    elseif(abi STREQUAL "armeabi-v7a")
        set(${ret} "armv7a-linux-androideabi" PARENT_SCOPE)
    elseif(abi STREQUAL "x86")
        set(${ret} "i686-linux-android" PARENT_SCOPE)
    elseif(abi STREQUAL "x86_64")
        set(${ret} "x86_64-linux-android" PARENT_SCOPE)
    else()
        message(FATAL_ERROR "Unknown Android ABI provided: ${abi}")
    endif()
endfunction()
